/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InternalApiCatCatResponse,
  InternalApiCatCreateCatRequest,
  InternalApiCatCreateCatResponse,
  InternalApiCatListCatsResponse,
  InternalApiCatUpdateCatRequest,
  RichmondApiInternalApiErrorsErrorResponse,
} from '../models/index';
import {
    InternalApiCatCatResponseFromJSON,
    InternalApiCatCatResponseToJSON,
    InternalApiCatCreateCatRequestFromJSON,
    InternalApiCatCreateCatRequestToJSON,
    InternalApiCatCreateCatResponseFromJSON,
    InternalApiCatCreateCatResponseToJSON,
    InternalApiCatListCatsResponseFromJSON,
    InternalApiCatListCatsResponseToJSON,
    InternalApiCatUpdateCatRequestFromJSON,
    InternalApiCatUpdateCatRequestToJSON,
    RichmondApiInternalApiErrorsErrorResponseFromJSON,
    RichmondApiInternalApiErrorsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1CatAllGetRequest {
    limit?: number;
    offset?: number;
}

export interface ApiV1CatIdDeleteRequest {
    id: number;
    authorization: string;
}

export interface ApiV1CatIdGetRequest {
    id: number;
}

export interface ApiV1CatIdPutRequest {
    id: number;
    authorization: string;
    data: InternalApiCatUpdateCatRequest;
}

export interface ApiV1CatNewPostRequest {
    authorization: string;
    data: string;
    file: Array<Blob>;
}

/**
 * 
 */
export class CatApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1CatAllGet without sending the request
     */
    async apiV1CatAllGetRequestOpts(requestParameters: ApiV1CatAllGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/cat/all`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists cats with pagination (no auth required)
     * List all cats
     */
    async apiV1CatAllGetRaw(requestParameters: ApiV1CatAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiCatListCatsResponse>> {
        const requestOptions = await this.apiV1CatAllGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiCatListCatsResponseFromJSON(jsonValue));
    }

    /**
     * Lists cats with pagination (no auth required)
     * List all cats
     */
    async apiV1CatAllGet(requestParameters: ApiV1CatAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiCatListCatsResponse> {
        const response = await this.apiV1CatAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1CatIdDelete without sending the request
     */
    async apiV1CatIdDeleteRequestOpts(requestParameters: ApiV1CatIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1CatIdDelete().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1CatIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/cat/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a cat by ID (auth required, must be owner)
     * Delete a cat
     */
    async apiV1CatIdDeleteRaw(requestParameters: ApiV1CatIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiV1CatIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a cat by ID (auth required, must be owner)
     * Delete a cat
     */
    async apiV1CatIdDelete(requestParameters: ApiV1CatIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1CatIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiV1CatIdGet without sending the request
     */
    async apiV1CatIdGetRequestOpts(requestParameters: ApiV1CatIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1CatIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/cat/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a cat with photos by ID
     * Get a cat by ID
     */
    async apiV1CatIdGetRaw(requestParameters: ApiV1CatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiCatCatResponse>> {
        const requestOptions = await this.apiV1CatIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiCatCatResponseFromJSON(jsonValue));
    }

    /**
     * Gets a cat with photos by ID
     * Get a cat by ID
     */
    async apiV1CatIdGet(requestParameters: ApiV1CatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiCatCatResponse> {
        const response = await this.apiV1CatIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1CatIdPut without sending the request
     */
    async apiV1CatIdPutRequestOpts(requestParameters: ApiV1CatIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1CatIdPut().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1CatIdPut().'
            );
        }

        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling apiV1CatIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/cat/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InternalApiCatUpdateCatRequestToJSON(requestParameters['data']),
        };
    }

    /**
     * Updates a cat by ID (auth required, must be owner)
     * Update a cat
     */
    async apiV1CatIdPutRaw(requestParameters: ApiV1CatIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiCatCatResponse>> {
        const requestOptions = await this.apiV1CatIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiCatCatResponseFromJSON(jsonValue));
    }

    /**
     * Updates a cat by ID (auth required, must be owner)
     * Update a cat
     */
    async apiV1CatIdPut(requestParameters: ApiV1CatIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiCatCatResponse> {
        const response = await this.apiV1CatIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1CatNewPost without sending the request
     */
    async apiV1CatNewPostRequestOpts(requestParameters: ApiV1CatNewPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1CatNewPost().'
            );
        }

        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling apiV1CatNewPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiV1CatNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['data'] != null) {
            formParams.append('data', requestParameters['data'] as any);
        }

        if (requestParameters['file'] != null) {
            requestParameters['file'].forEach((element) => {
                formParams.append('file', element as any);
            })
        }


        let urlPath = `/api/v1/cat/new`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Creates a new cat with photos (multipart/form-data)
     * Create a new cat
     */
    async apiV1CatNewPostRaw(requestParameters: ApiV1CatNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiCatCreateCatResponse>> {
        const requestOptions = await this.apiV1CatNewPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiCatCreateCatResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new cat with photos (multipart/form-data)
     * Create a new cat
     */
    async apiV1CatNewPost(requestParameters: ApiV1CatNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiCatCreateCatResponse> {
        const response = await this.apiV1CatNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
