/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RichmondApiInternalApiErrorsErrorResponse,
} from '../models/index';
import {
    RichmondApiInternalApiErrorsErrorResponseFromJSON,
    RichmondApiInternalApiErrorsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1FileKeyGetRequest {
    key: string;
    quality?: ApiV1FileKeyGetQualityEnum;
}

/**
 * 
 */
export class FileApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1FileKeyGet without sending the request
     */
    async apiV1FileKeyGetRequestOpts(requestParameters: ApiV1FileKeyGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiV1FileKeyGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/file/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Downloads a file by key from S3 storage
     * Download a file from S3
     */
    async apiV1FileKeyGetRaw(requestParameters: ApiV1FileKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.apiV1FileKeyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Downloads a file by key from S3 storage
     * Download a file from S3
     */
    async apiV1FileKeyGet(requestParameters: ApiV1FileKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1FileKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiV1FileKeyGetQualityEnum = {
    Original: 'original',
    Thumbnail: 'thumbnail',
    Preview: 'preview'
} as const;
export type ApiV1FileKeyGetQualityEnum = typeof ApiV1FileKeyGetQualityEnum[keyof typeof ApiV1FileKeyGetQualityEnum];
