/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InternalApiPostListPostsResponse,
  InternalApiPostPostResponse,
  InternalApiPostUpdatePostRequest,
  RichmondApiInternalApiErrorsErrorResponse,
} from '../models/index';
import {
    InternalApiPostListPostsResponseFromJSON,
    InternalApiPostListPostsResponseToJSON,
    InternalApiPostPostResponseFromJSON,
    InternalApiPostPostResponseToJSON,
    InternalApiPostUpdatePostRequestFromJSON,
    InternalApiPostUpdatePostRequestToJSON,
    RichmondApiInternalApiErrorsErrorResponseFromJSON,
    RichmondApiInternalApiErrorsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1PostAllGetRequest {
    limit?: number;
    offset?: number;
}

export interface ApiV1PostIdDeleteRequest {
    id: number;
    authorization: string;
}

export interface ApiV1PostIdGetRequest {
    id: number;
}

export interface ApiV1PostIdPutRequest {
    id: number;
    authorization: string;
    data: InternalApiPostUpdatePostRequest;
}

export interface ApiV1PostNewPostRequest {
    authorization: string;
    data: string;
    file: Array<Blob>;
}

/**
 * 
 */
export class PostApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1PostAllGet without sending the request
     */
    async apiV1PostAllGetRequestOpts(requestParameters: ApiV1PostAllGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/post/all`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists posts with pagination (no auth required)
     * List all posts
     */
    async apiV1PostAllGetRaw(requestParameters: ApiV1PostAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiPostListPostsResponse>> {
        const requestOptions = await this.apiV1PostAllGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiPostListPostsResponseFromJSON(jsonValue));
    }

    /**
     * Lists posts with pagination (no auth required)
     * List all posts
     */
    async apiV1PostAllGet(requestParameters: ApiV1PostAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiPostListPostsResponse> {
        const response = await this.apiV1PostAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1PostIdDelete without sending the request
     */
    async apiV1PostIdDeleteRequestOpts(requestParameters: ApiV1PostIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1PostIdDelete().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1PostIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/post/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a post by ID (auth required, must be owner)
     * Delete a post
     */
    async apiV1PostIdDeleteRaw(requestParameters: ApiV1PostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiV1PostIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a post by ID (auth required, must be owner)
     * Delete a post
     */
    async apiV1PostIdDelete(requestParameters: ApiV1PostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PostIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiV1PostIdGet without sending the request
     */
    async apiV1PostIdGetRequestOpts(requestParameters: ApiV1PostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1PostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/post/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a post by ID
     * Get a post by ID
     */
    async apiV1PostIdGetRaw(requestParameters: ApiV1PostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiPostPostResponse>> {
        const requestOptions = await this.apiV1PostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiPostPostResponseFromJSON(jsonValue));
    }

    /**
     * Gets a post by ID
     * Get a post by ID
     */
    async apiV1PostIdGet(requestParameters: ApiV1PostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiPostPostResponse> {
        const response = await this.apiV1PostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1PostIdPut without sending the request
     */
    async apiV1PostIdPutRequestOpts(requestParameters: ApiV1PostIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1PostIdPut().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1PostIdPut().'
            );
        }

        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling apiV1PostIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/post/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InternalApiPostUpdatePostRequestToJSON(requestParameters['data']),
        };
    }

    /**
     * Updates a post by ID (auth required, must be owner)
     * Update a post
     */
    async apiV1PostIdPutRaw(requestParameters: ApiV1PostIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiPostPostResponse>> {
        const requestOptions = await this.apiV1PostIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiPostPostResponseFromJSON(jsonValue));
    }

    /**
     * Updates a post by ID (auth required, must be owner)
     * Update a post
     */
    async apiV1PostIdPut(requestParameters: ApiV1PostIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiPostPostResponse> {
        const response = await this.apiV1PostIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1PostNewPost without sending the request
     */
    async apiV1PostNewPostRequestOpts(requestParameters: ApiV1PostNewPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1PostNewPost().'
            );
        }

        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling apiV1PostNewPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiV1PostNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['data'] != null) {
            formParams.append('data', requestParameters['data'] as any);
        }

        if (requestParameters['file'] != null) {
            requestParameters['file'].forEach((element) => {
                formParams.append('file', element as any);
            })
        }


        let urlPath = `/api/v1/post/new`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Creates a new post for a cat with photos (multipart/form-data)
     * Create a new post
     */
    async apiV1PostNewPostRaw(requestParameters: ApiV1PostNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiPostPostResponse>> {
        const requestOptions = await this.apiV1PostNewPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiPostPostResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new post for a cat with photos (multipart/form-data)
     * Create a new post
     */
    async apiV1PostNewPost(requestParameters: ApiV1PostNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiPostPostResponse> {
        const response = await this.apiV1PostNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
