/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InternalApiUserCreateRequest,
  InternalApiUserLoginRequest,
  InternalApiUserTokenResponse,
  InternalApiUserUserResponse,
  RichmondApiInternalApiErrorsErrorResponse,
} from '../models/index';
import {
    InternalApiUserCreateRequestFromJSON,
    InternalApiUserCreateRequestToJSON,
    InternalApiUserLoginRequestFromJSON,
    InternalApiUserLoginRequestToJSON,
    InternalApiUserTokenResponseFromJSON,
    InternalApiUserTokenResponseToJSON,
    InternalApiUserUserResponseFromJSON,
    InternalApiUserUserResponseToJSON,
    RichmondApiInternalApiErrorsErrorResponseFromJSON,
    RichmondApiInternalApiErrorsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1UserGetRequest {
    authorization: string;
}

export interface ApiV1UserLoginPostRequest {
    request: InternalApiUserLoginRequest;
}

export interface ApiV1UserNewPostRequest {
    request: InternalApiUserCreateRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1UserGet without sending the request
     */
    async apiV1UserGetRequestOpts(requestParameters: ApiV1UserGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1UserGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns user data for authenticated user
     * Get current user
     */
    async apiV1UserGetRaw(requestParameters: ApiV1UserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiUserUserResponse>> {
        const requestOptions = await this.apiV1UserGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiUserUserResponseFromJSON(jsonValue));
    }

    /**
     * Returns user data for authenticated user
     * Get current user
     */
    async apiV1UserGet(requestParameters: ApiV1UserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiUserUserResponse> {
        const response = await this.apiV1UserGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1UserLoginPost without sending the request
     */
    async apiV1UserLoginPostRequestOpts(requestParameters: ApiV1UserLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1UserLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/user/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InternalApiUserLoginRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Login with credentials, returns auth token
     * Login
     */
    async apiV1UserLoginPostRaw(requestParameters: ApiV1UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiUserTokenResponse>> {
        const requestOptions = await this.apiV1UserLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiUserTokenResponseFromJSON(jsonValue));
    }

    /**
     * Login with credentials, returns auth token
     * Login
     */
    async apiV1UserLoginPost(requestParameters: ApiV1UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiUserTokenResponse> {
        const response = await this.apiV1UserLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1UserNewPost without sending the request
     */
    async apiV1UserNewPostRequestOpts(requestParameters: ApiV1UserNewPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1UserNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/user/new`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InternalApiUserCreateRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Creates a new user with hashed password
     * Create a new user
     */
    async apiV1UserNewPostRaw(requestParameters: ApiV1UserNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalApiUserUserResponse>> {
        const requestOptions = await this.apiV1UserNewPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalApiUserUserResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new user with hashed password
     * Create a new user
     */
    async apiV1UserNewPost(requestParameters: ApiV1UserNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalApiUserUserResponse> {
        const response = await this.apiV1UserNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
