import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Пушистик дня',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen bg-background text-foreground`}>
            <Providers>
                <Header />
                <main
                    className="flex-1 max-w-[1280px] w-full mx-auto px-0 sx:px-4 lg:px-0 py-0"
                    style={{ minHeight: 'calc(100vh - 150px)' }}
                >
                    {children}
                </main>
                <Footer />
            </Providers>
        </body>
    </html>
);

export default RootLayout;
