/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiHealthHealthResponse
 */
export interface InternalApiHealthHealthResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalApiHealthHealthResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the InternalApiHealthHealthResponse interface.
 */
export function instanceOfInternalApiHealthHealthResponse(value: object): value is InternalApiHealthHealthResponse {
    return true;
}

export function InternalApiHealthHealthResponseFromJSON(json: any): InternalApiHealthHealthResponse {
    return InternalApiHealthHealthResponseFromJSONTyped(json, false);
}

export function InternalApiHealthHealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiHealthHealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InternalApiHealthHealthResponseToJSON(json: any): InternalApiHealthHealthResponse {
    return InternalApiHealthHealthResponseToJSONTyped(json, false);
}

export function InternalApiHealthHealthResponseToJSONTyped(value?: InternalApiHealthHealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

