/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiUserLoginRequest
 */
export interface InternalApiUserLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserLoginRequest
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the InternalApiUserLoginRequest interface.
 */
export function instanceOfInternalApiUserLoginRequest(value: object): value is InternalApiUserLoginRequest {
    if (!('login' in value) || value['login'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function InternalApiUserLoginRequestFromJSON(json: any): InternalApiUserLoginRequest {
    return InternalApiUserLoginRequestFromJSONTyped(json, false);
}

export function InternalApiUserLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiUserLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function InternalApiUserLoginRequestToJSON(json: any): InternalApiUserLoginRequest {
    return InternalApiUserLoginRequestToJSONTyped(json, false);
}

export function InternalApiUserLoginRequestToJSONTyped(value?: InternalApiUserLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

