/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalApiCatFileMetadata } from './InternalApiCatFileMetadata';
import {
    InternalApiCatFileMetadataFromJSON,
    InternalApiCatFileMetadataFromJSONTyped,
    InternalApiCatFileMetadataToJSON,
    InternalApiCatFileMetadataToJSONTyped,
} from './InternalApiCatFileMetadata';

/**
 * 
 * @export
 * @interface InternalApiCatCatResponse
 */
export interface InternalApiCatCatResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCatResponse
     */
    birthDate?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCatResponse
     */
    breed?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatCatResponse
     */
    catId?: number;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCatResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<InternalApiCatFileMetadata>}
     * @memberof InternalApiCatCatResponse
     */
    galleryPhotos?: Array<InternalApiCatFileMetadata>;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCatResponse
     */
    habits?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCatResponse
     */
    name?: string;
    /**
     * 
     * @type {InternalApiCatFileMetadata}
     * @memberof InternalApiCatCatResponse
     */
    titlePhoto?: InternalApiCatFileMetadata;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatCatResponse
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatCatResponse
     */
    weight?: number;
}

/**
 * Check if a given object implements the InternalApiCatCatResponse interface.
 */
export function instanceOfInternalApiCatCatResponse(value: object): value is InternalApiCatCatResponse {
    return true;
}

export function InternalApiCatCatResponseFromJSON(json: any): InternalApiCatCatResponse {
    return InternalApiCatCatResponseFromJSONTyped(json, false);
}

export function InternalApiCatCatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiCatCatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'birthDate': json['birthDate'] == null ? undefined : json['birthDate'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'catId': json['catId'] == null ? undefined : json['catId'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'galleryPhotos': json['galleryPhotos'] == null ? undefined : ((json['galleryPhotos'] as Array<any>).map(InternalApiCatFileMetadataFromJSON)),
        'habits': json['habits'] == null ? undefined : json['habits'],
        'name': json['name'] == null ? undefined : json['name'],
        'titlePhoto': json['titlePhoto'] == null ? undefined : InternalApiCatFileMetadataFromJSON(json['titlePhoto']),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function InternalApiCatCatResponseToJSON(json: any): InternalApiCatCatResponse {
    return InternalApiCatCatResponseToJSONTyped(json, false);
}

export function InternalApiCatCatResponseToJSONTyped(value?: InternalApiCatCatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'birthDate': value['birthDate'],
        'breed': value['breed'],
        'catId': value['catId'],
        'createdAt': value['createdAt'],
        'galleryPhotos': value['galleryPhotos'] == null ? undefined : ((value['galleryPhotos'] as Array<any>).map(InternalApiCatFileMetadataToJSON)),
        'habits': value['habits'],
        'name': value['name'],
        'titlePhoto': InternalApiCatFileMetadataToJSON(value['titlePhoto']),
        'userId': value['userId'],
        'weight': value['weight'],
    };
}

