/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalApiPostPostResponse } from './InternalApiPostPostResponse';
import {
    InternalApiPostPostResponseFromJSON,
    InternalApiPostPostResponseFromJSONTyped,
    InternalApiPostPostResponseToJSON,
    InternalApiPostPostResponseToJSONTyped,
} from './InternalApiPostPostResponse';

/**
 * 
 * @export
 * @interface InternalApiPostListPostsResponse
 */
export interface InternalApiPostListPostsResponse {
    /**
     * 
     * @type {number}
     * @memberof InternalApiPostListPostsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof InternalApiPostListPostsResponse
     */
    offset?: number;
    /**
     * 
     * @type {Array<InternalApiPostPostResponse>}
     * @memberof InternalApiPostListPostsResponse
     */
    posts?: Array<InternalApiPostPostResponse>;
    /**
     * 
     * @type {number}
     * @memberof InternalApiPostListPostsResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the InternalApiPostListPostsResponse interface.
 */
export function instanceOfInternalApiPostListPostsResponse(value: object): value is InternalApiPostListPostsResponse {
    return true;
}

export function InternalApiPostListPostsResponseFromJSON(json: any): InternalApiPostListPostsResponse {
    return InternalApiPostListPostsResponseFromJSONTyped(json, false);
}

export function InternalApiPostListPostsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiPostListPostsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(InternalApiPostPostResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function InternalApiPostListPostsResponseToJSON(json: any): InternalApiPostListPostsResponse {
    return InternalApiPostListPostsResponseToJSONTyped(json, false);
}

export function InternalApiPostListPostsResponseToJSONTyped(value?: InternalApiPostListPostsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(InternalApiPostPostResponseToJSON)),
        'total': value['total'],
    };
}

