/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiUserTokenResponse
 */
export interface InternalApiUserTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserTokenResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the InternalApiUserTokenResponse interface.
 */
export function instanceOfInternalApiUserTokenResponse(value: object): value is InternalApiUserTokenResponse {
    return true;
}

export function InternalApiUserTokenResponseFromJSON(json: any): InternalApiUserTokenResponse {
    return InternalApiUserTokenResponseFromJSONTyped(json, false);
}

export function InternalApiUserTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiUserTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function InternalApiUserTokenResponseToJSON(json: any): InternalApiUserTokenResponse {
    return InternalApiUserTokenResponseToJSONTyped(json, false);
}

export function InternalApiUserTokenResponseToJSONTyped(value?: InternalApiUserTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

