/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiUserCreateRequest
 */
export interface InternalApiUserCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserCreateRequest
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserCreateRequest
     */
    password: string;
}

/**
 * Check if a given object implements the InternalApiUserCreateRequest interface.
 */
export function instanceOfInternalApiUserCreateRequest(value: object): value is InternalApiUserCreateRequest {
    if (!('login' in value) || value['login'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function InternalApiUserCreateRequestFromJSON(json: any): InternalApiUserCreateRequest {
    return InternalApiUserCreateRequestFromJSONTyped(json, false);
}

export function InternalApiUserCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiUserCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function InternalApiUserCreateRequestToJSON(json: any): InternalApiUserCreateRequest {
    return InternalApiUserCreateRequestToJSONTyped(json, false);
}

export function InternalApiUserCreateRequestToJSONTyped(value?: InternalApiUserCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

