/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiCatCreateCatRequest
 */
export interface InternalApiCatCreateCatRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCreateCatRequest
     */
    birthDate?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCreateCatRequest
     */
    breed?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCreateCatRequest
     */
    habits?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCreateCatRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatCreateCatRequest
     */
    weight?: number;
}

/**
 * Check if a given object implements the InternalApiCatCreateCatRequest interface.
 */
export function instanceOfInternalApiCatCreateCatRequest(value: object): value is InternalApiCatCreateCatRequest {
    return true;
}

export function InternalApiCatCreateCatRequestFromJSON(json: any): InternalApiCatCreateCatRequest {
    return InternalApiCatCreateCatRequestFromJSONTyped(json, false);
}

export function InternalApiCatCreateCatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiCatCreateCatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'birthDate': json['birthDate'] == null ? undefined : json['birthDate'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'habits': json['habits'] == null ? undefined : json['habits'],
        'name': json['name'] == null ? undefined : json['name'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function InternalApiCatCreateCatRequestToJSON(json: any): InternalApiCatCreateCatRequest {
    return InternalApiCatCreateCatRequestToJSONTyped(json, false);
}

export function InternalApiCatCreateCatRequestToJSONTyped(value?: InternalApiCatCreateCatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'birthDate': value['birthDate'],
        'breed': value['breed'],
        'habits': value['habits'],
        'name': value['name'],
        'weight': value['weight'],
    };
}

