/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RichmondApiInternalApiFileutilFileMetadata } from './RichmondApiInternalApiFileutilFileMetadata';
import {
    RichmondApiInternalApiFileutilFileMetadataFromJSON,
    RichmondApiInternalApiFileutilFileMetadataFromJSONTyped,
    RichmondApiInternalApiFileutilFileMetadataToJSON,
    RichmondApiInternalApiFileutilFileMetadataToJSONTyped,
} from './RichmondApiInternalApiFileutilFileMetadata';

/**
 * 
 * @export
 * @interface InternalApiPostPostResponse
 */
export interface InternalApiPostPostResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostPostResponse
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostPostResponse
     */
    catId?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostPostResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<RichmondApiInternalApiFileutilFileMetadata>}
     * @memberof InternalApiPostPostResponse
     */
    photos?: Array<RichmondApiInternalApiFileutilFileMetadata>;
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostPostResponse
     */
    postId?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostPostResponse
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalApiPostPostResponse
     */
    userId?: number;
}

/**
 * Check if a given object implements the InternalApiPostPostResponse interface.
 */
export function instanceOfInternalApiPostPostResponse(value: object): value is InternalApiPostPostResponse {
    return true;
}

export function InternalApiPostPostResponseFromJSON(json: any): InternalApiPostPostResponse {
    return InternalApiPostPostResponseFromJSONTyped(json, false);
}

export function InternalApiPostPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiPostPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'catId': json['catId'] == null ? undefined : json['catId'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'photos': json['photos'] == null ? undefined : ((json['photos'] as Array<any>).map(RichmondApiInternalApiFileutilFileMetadataFromJSON)),
        'postId': json['postId'] == null ? undefined : json['postId'],
        'title': json['title'] == null ? undefined : json['title'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function InternalApiPostPostResponseToJSON(json: any): InternalApiPostPostResponse {
    return InternalApiPostPostResponseToJSONTyped(json, false);
}

export function InternalApiPostPostResponseToJSONTyped(value?: InternalApiPostPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'catId': value['catId'],
        'createdAt': value['createdAt'],
        'photos': value['photos'] == null ? undefined : ((value['photos'] as Array<any>).map(RichmondApiInternalApiFileutilFileMetadataToJSON)),
        'postId': value['postId'],
        'title': value['title'],
        'userId': value['userId'],
    };
}

