/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalApiCatFileMetadata } from './InternalApiCatFileMetadata';
import {
    InternalApiCatFileMetadataFromJSON,
    InternalApiCatFileMetadataFromJSONTyped,
    InternalApiCatFileMetadataToJSON,
    InternalApiCatFileMetadataToJSONTyped,
} from './InternalApiCatFileMetadata';

/**
 * 
 * @export
 * @interface InternalApiCatCreateCatResponse
 */
export interface InternalApiCatCreateCatResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatCreateCatResponse
     */
    catId?: string;
    /**
     * 
     * @type {Array<InternalApiCatFileMetadata>}
     * @memberof InternalApiCatCreateCatResponse
     */
    galleryPhotos?: Array<InternalApiCatFileMetadata>;
    /**
     * 
     * @type {InternalApiCatFileMetadata}
     * @memberof InternalApiCatCreateCatResponse
     */
    titlePhoto?: InternalApiCatFileMetadata;
}

/**
 * Check if a given object implements the InternalApiCatCreateCatResponse interface.
 */
export function instanceOfInternalApiCatCreateCatResponse(value: object): value is InternalApiCatCreateCatResponse {
    return true;
}

export function InternalApiCatCreateCatResponseFromJSON(json: any): InternalApiCatCreateCatResponse {
    return InternalApiCatCreateCatResponseFromJSONTyped(json, false);
}

export function InternalApiCatCreateCatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiCatCreateCatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'catId': json['catId'] == null ? undefined : json['catId'],
        'galleryPhotos': json['galleryPhotos'] == null ? undefined : ((json['galleryPhotos'] as Array<any>).map(InternalApiCatFileMetadataFromJSON)),
        'titlePhoto': json['titlePhoto'] == null ? undefined : InternalApiCatFileMetadataFromJSON(json['titlePhoto']),
    };
}

export function InternalApiCatCreateCatResponseToJSON(json: any): InternalApiCatCreateCatResponse {
    return InternalApiCatCreateCatResponseToJSONTyped(json, false);
}

export function InternalApiCatCreateCatResponseToJSONTyped(value?: InternalApiCatCreateCatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catId': value['catId'],
        'galleryPhotos': value['galleryPhotos'] == null ? undefined : ((value['galleryPhotos'] as Array<any>).map(InternalApiCatFileMetadataToJSON)),
        'titlePhoto': InternalApiCatFileMetadataToJSON(value['titlePhoto']),
    };
}

