/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiPostUpdatePostRequest
 */
export interface InternalApiPostUpdatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostUpdatePostRequest
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiPostUpdatePostRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the InternalApiPostUpdatePostRequest interface.
 */
export function instanceOfInternalApiPostUpdatePostRequest(value: object): value is InternalApiPostUpdatePostRequest {
    return true;
}

export function InternalApiPostUpdatePostRequestFromJSON(json: any): InternalApiPostUpdatePostRequest {
    return InternalApiPostUpdatePostRequestFromJSONTyped(json, false);
}

export function InternalApiPostUpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiPostUpdatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function InternalApiPostUpdatePostRequestToJSON(json: any): InternalApiPostUpdatePostRequest {
    return InternalApiPostUpdatePostRequestToJSONTyped(json, false);
}

export function InternalApiPostUpdatePostRequestToJSONTyped(value?: InternalApiPostUpdatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'title': value['title'],
    };
}

