/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalApiCatCatResponse } from './InternalApiCatCatResponse';
import {
    InternalApiCatCatResponseFromJSON,
    InternalApiCatCatResponseFromJSONTyped,
    InternalApiCatCatResponseToJSON,
    InternalApiCatCatResponseToJSONTyped,
} from './InternalApiCatCatResponse';

/**
 * 
 * @export
 * @interface InternalApiCatListCatsResponse
 */
export interface InternalApiCatListCatsResponse {
    /**
     * 
     * @type {Array<InternalApiCatCatResponse>}
     * @memberof InternalApiCatListCatsResponse
     */
    cats?: Array<InternalApiCatCatResponse>;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatListCatsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatListCatsResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatListCatsResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the InternalApiCatListCatsResponse interface.
 */
export function instanceOfInternalApiCatListCatsResponse(value: object): value is InternalApiCatListCatsResponse {
    return true;
}

export function InternalApiCatListCatsResponseFromJSON(json: any): InternalApiCatListCatsResponse {
    return InternalApiCatListCatsResponseFromJSONTyped(json, false);
}

export function InternalApiCatListCatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiCatListCatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cats': json['cats'] == null ? undefined : ((json['cats'] as Array<any>).map(InternalApiCatCatResponseFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function InternalApiCatListCatsResponseToJSON(json: any): InternalApiCatListCatsResponse {
    return InternalApiCatListCatsResponseToJSONTyped(json, false);
}

export function InternalApiCatListCatsResponseToJSONTyped(value?: InternalApiCatListCatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cats': value['cats'] == null ? undefined : ((value['cats'] as Array<any>).map(InternalApiCatCatResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

