/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichmondApiInternalApiFileutilFileMetadata
 */
export interface RichmondApiInternalApiFileutilFileMetadata {
    /**
     * 
     * @type {number}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    key?: string;
    /**
     * 
     * @type {number}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof RichmondApiInternalApiFileutilFileMetadata
     */
    width?: number;
}

/**
 * Check if a given object implements the RichmondApiInternalApiFileutilFileMetadata interface.
 */
export function instanceOfRichmondApiInternalApiFileutilFileMetadata(value: object): value is RichmondApiInternalApiFileutilFileMetadata {
    return true;
}

export function RichmondApiInternalApiFileutilFileMetadataFromJSON(json: any): RichmondApiInternalApiFileutilFileMetadata {
    return RichmondApiInternalApiFileutilFileMetadataFromJSONTyped(json, false);
}

export function RichmondApiInternalApiFileutilFileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichmondApiInternalApiFileutilFileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'key': json['key'] == null ? undefined : json['key'],
        'size': json['size'] == null ? undefined : json['size'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function RichmondApiInternalApiFileutilFileMetadataToJSON(json: any): RichmondApiInternalApiFileutilFileMetadata {
    return RichmondApiInternalApiFileutilFileMetadataToJSONTyped(json, false);
}

export function RichmondApiInternalApiFileutilFileMetadataToJSONTyped(value?: RichmondApiInternalApiFileutilFileMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'key': value['key'],
        'size': value['size'],
        'type': value['type'],
        'url': value['url'],
        'width': value['width'],
    };
}

