/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichmondApiInternalApiErrorsErrorResponse
 */
export interface RichmondApiInternalApiErrorsErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof RichmondApiInternalApiErrorsErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the RichmondApiInternalApiErrorsErrorResponse interface.
 */
export function instanceOfRichmondApiInternalApiErrorsErrorResponse(value: object): value is RichmondApiInternalApiErrorsErrorResponse {
    return true;
}

export function RichmondApiInternalApiErrorsErrorResponseFromJSON(json: any): RichmondApiInternalApiErrorsErrorResponse {
    return RichmondApiInternalApiErrorsErrorResponseFromJSONTyped(json, false);
}

export function RichmondApiInternalApiErrorsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichmondApiInternalApiErrorsErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function RichmondApiInternalApiErrorsErrorResponseToJSON(json: any): RichmondApiInternalApiErrorsErrorResponse {
    return RichmondApiInternalApiErrorsErrorResponseToJSONTyped(json, false);
}

export function RichmondApiInternalApiErrorsErrorResponseToJSONTyped(value?: RichmondApiInternalApiErrorsErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

